---
name: deploying-actions
on: 
  pull_request:
    types: 
      - opened 
  workflow_dispatch: 
  push: 
    branches: 
      - main
      - dev
    paths: 
      - .github/workflow/* 
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install Dependencies
        run: npm ci
      - name: Test Code
        run: npm test
  deploy-job:
    needs: test-job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install Dependencies
        run: npm ci
      - name: Build the code
        run: npm run build
      - name: code artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: |
            dist
            package-json
      - name: deploying the code
        run: echo " deploying the code"
